### ISSUE TITLE
Simple example needed

### ISSUE THREAD

**Issue by xiaodaigh** [nlw0/ChipSort.jl#7]
I have `x = rand(Int, 128)` how do I sort this using ChipSort? `sort(x)` works great, but can't figure out how to do this with ChipSort.jl.

**Comment by nlw0** [comment]
Hi @xiaodaigh . Indeed, the documentation is lacking an explicit list of the offered functions. The main ones are actually the first exported in the beginning of the ChipSort.jl file: `chipsort_small!`, `chipsort_medium!`, `chipsort_large` and `chipsort!`, this last one appearing to perform best in most cases.

**Comment by nlw0** [comment]
https://github.com/nlw0/ChipSort.jl/blob/master/test/test-chipsort.jl has more examples. You'll usually like to set up some parameters.
